services:
  postgres:
    image: postgres:latest
    env_file:
      - path: ../scripts/.env
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    env_file:
      - path: ../scripts/.env
    ports:
      - "3000:3000"
    volumes:
      - ../data/grafana:/var/lib/grafana
      - ./setup-grafana.sh:/usr/local/bin/setup-grafana.sh
    depends_on:
      - postgres
    entrypoint: ["/usr/local/bin/setup-grafana.sh"]
